---
- hosts: 172.31.0.130
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install apache2 webserver
    apt: 
      name: apache2
      state: present
  - name: I want to copy static file into node side
    copy: 
      src: mytestfile
      dest: /home/ubuntu/
