---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu nodes
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  
  - name: I want to start apache2 webserver on ubuntu nodes
    service: 
        name: "{{myjavapackonubuntu}}"
        state: stopped 
    when: ansible_os_family=="Debian"

  - name: i want to install httpd webserver on redhat nodes
    dnf: 
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: I want to start httpd webserver on redhat nodes
    service: 
       name: "{{myjavapackonredhat}}"
       state: started
    when: ansible_os_family=="RedHat"