---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu nodes
    apt:
      name: apache2
      state: present
  
  - name: I want to start apache2 webserver on ubuntu nodes
    service: 
        name: apache2
        state: stopped 