---
- hosts: 172.31.0.130
  become: yes
  tasks: 
  - name: I want to execute linux commands
    command: hostname -f
    register: myfirsttaskresult

  - name: display myfirsttaskresult value
    debug: 
      msg: "{{myfirsttaskresult}}"

  - name: I want to install git
    apt: 
      name: git
      state: present
    when: myfirsttaskresult.stderr ==""

  - name: I want to install tree
    apt: 
      name: tree
      state: present
    when: myfirsttaskresult.stderr !=""